# 基础
## 1、轴的概念： ![2d](picture/2d.png)
         注意：一维数组只有轴0：![1d](picture/1d.png)
         
## >2、array的属性：（ndarray = n dimension array）
#### ndarray.ndim：数列的维度，即轴数

#### ndarray.shape：以元组的形式显示数列的形状，如（1，2，3）即为一行二列三层的数组

#### ndarray.size：数组中的元素总数

#### ndarray.dtype：数组中元素的数据类型，除了python中的numpy中也有自己独特的数据类型如：int32，int16，float64。。。

#### ndarray.itemsize：数组中元素的字节数，如float64字节数为8（64/8）

## >示例：

In [6]:
import numpy as np

a = np.arange(9).reshape(3,3) #将0~9的整数，重整为一个三行三列的数列
print(a)

print("\n轴数： " ,a.ndim)
print("形状: " ,a.shape)
print("元素总数： ", a.size)
print("数据类型： " ,a.dtype)
print("一个数据的字节数： " ,a.itemsize)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

轴数：  2
形状:  (3, 3)
元素总数：  9
数据类型：  int32
一个数据的字节数：  4


## 3、基础操作

### 1、创建数组
#### 1、直接创建（要用列表或元组来创建）

In [17]:
import numpy as np

a = np.array([1,2,3,4]) #用列表创建
b = np.array((4,5,6,7)) #用元组创建
c = np.array([[1,2,3],[4,5,6]] ,dtype=complex) #用列表框住多个列表或元组创建多维数组，用dtype可定义数据类型
print(a)
print(b)
print(c)

"""这样将报错"""
#c = np.array(1,2,3,4)
""""""""""""""""""""""""

[1 2 3 4]
[4 5 6 7]
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


''

#### 2、创建给定数组
##### 1、全零组  ：zeros(形状元组)

In [14]:
import numpy as np

z = np.zeros((3,4)) 
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


##### 2、全一组 ：ones（形状元组）

In [15]:
import numpy as np

o = np.ones((3,4)) 
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


##### 3、乱数组 ： empty（形状元组）

In [18]:
import numpy as np

e = np.empty((3,4)) 
print(e)

[[1. 0. 2. 0.]
 [3. 0. 4. 0.]
 [5. 0. 6. 0.]]


##### 5、用arange（始，末，步长）来创建数组  ：注当步长为小数时，元素个数可能不确定（不可数），所以用linspace（始，末，元素个数）来创建

In [22]:
import numpy as np

a = np.arange(1,8,2) #创建从1到8，步长间隔为2的数组
b = np.arange(1,8,0.5) #创建从1到8，步长间隔为0.5的数组
c = np.linspace(1,8,6) #创建从1到8，有6个元素的数组
print(a)
print(b)
print(c)

[1 3 5 7]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]
[1.  2.4 3.8 5.2 6.6 8. ]


##### 6、用随机数生成
**随机数**
<img src=https://img-blog.csdnimg.cn/img_convert/38a43c77d06c40bb4d629c5102389b8d.png>

In [ ]:
import numpy as np

a = np.random.random((3,4))  #生成两行三列的随机数
print(a)

b = np.floor(10*a)  # floor即地板数，即向下取整，即高数中的[x]
print(b)

### 2、打印数组
#### 一维：np.array(x) ；二维：np.array(x,y) ; 三维：np.array(h,x,y)

In [32]:
import numpy as np

d1 = np.arange(18) #单行数组
d2 = np.arange(18).reshape((3,6)) #三行六列数组
d3 = np.arange(18).reshape((3,2,3)) #三层两行三列数组
print(d1,"\n")
print(d2,"\n")
print(d3,"\n")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17] 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]] 

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]] 



### 3、数组，矩阵运算
#### 1、乘法运算

In [37]:
import numpy as np

a = np.arange(9).reshape((3,3))
b = np.array([[1,4,3],[2,4,6],[1,3,2]])
print(a,'\n')
print(b,'\n')

c = a.dot(b) #矩阵乘法在numpy中表现为dot product ，a·b为外积即矩阵乘法。
print(c,'\n')

d = a*b      #矩阵逐项对成在numpy中表现为 * ，即第一项乘第一项，第二项乘第二项。。。。
print(d,'\n')

a += a #自己累加处理，乘法也可以这样
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[1 4 3]
 [2 4 6]
 [1 3 2]] 

[[ 4 10 10]
 [16 43 43]
 [28 76 76]] 

[[ 0  4  6]
 [ 6 16 30]
 [ 6 21 16]] 

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


#### 2、元素求和，最值，中值，平均值  (可指定轴)

In [42]:
import numpy as np

b = np.array([[1,4,3],[2,4,6],[1,3,2]])
print(b,'\n')

print(b.sum() ,'\n')    #矩阵各元素之和
print(b.sum(axis=0),'\n')  #矩阵沿着 0轴 ，即列轴，相加
print(b.min(),'\n')     #矩阵各元素的最小值
print(b.max(axis=1),'\n')  #矩阵沿着 1轴，即行轴，的最大值
print(np.median(b,axis=1),'\n') #矩阵沿着 1轴 的中值
print(np.mean(b,axis=0),'\n') #矩阵沿着 0 轴的平均值

[[1 4 3]
 [2 4 6]
 [1 3 2]] 

26 

[ 4 11 11] 

1 

[4 6 3] 

[3. 4. 2.] 

[1.33333333 3.66666667 3.66666667] 



#### 3、三角运算 (三角函数输入为弧度，反三角函数输出为弧度)

In [52]:
import numpy as np

b = np.array([0,30,60,90])
sin = np.sin(b*np.pi/180)  #三角函数输入必须为弧度，即角度乘以 Π/180

print(b,'\n')
print(sin)

inv = np.arcsin(sin)      #反三角函数输出也为弧度值
degree = np.degrees(inv)  #所以通过 np.degrees() 函数将弧度转化为角度
print(degree)


[ 0 30 60 90] 

[0.        0.5       0.8660254 1.       ]
[ 0. 30. 60. 90.]


#### 4、常用运算

In [64]:
import numpy as np

a = np.array([0,1,2])
b = np.array([[1,4,3],[2,4,6],[1,3,2]])
print(b,'\n')
print(a,'\n')

ex = np.exp(a)  #输出为 e^x 的值，做的时 e 的幂指运算
print(ex)

sq = np.sqrt(a) #输出为数列的开平方
print(sq)
print('\n')

add = np.add(a,b) #a+b
print(add)
print('\n')

sub = np.subtract(a,b) #a-b
print(sub)
print('\n')

mul = np.multiply(a,b) #a*b
print(mul)
print('\n')

div = np.divide(a,b) #a/b
print(div)
print('\n')

[[1 4 3]
 [2 4 6]
 [1 3 2]] 

[0 1 2] 

[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


[[1 5 5]
 [2 5 8]
 [1 4 4]]


[[-1 -3 -1]
 [-2 -3 -4]
 [-1 -2  0]]


[[ 0  4  6]
 [ 0  4 12]
 [ 0  3  4]]


[[0.         0.25       0.66666667]
 [0.         0.25       0.33333333]
 [0.         0.33333333 1.        ]]




### 4、索引，切片，遍历
 **补充内容：利用函数创造数组：**
  >1. 定义一个关于（x，y）的函数def f (x,y);
  >2. 使用np.fromfunction（function_name ,(shape) ,dtype）;  
  >3. 函数中的x，y将自动按照从左到右的规律变化，如三行三列数列将这样（0，0），（0，1），（0，2），（1，0）.。。。“》》

In [87]:
import numpy as np

def f (x,y):
    return 10*x+y  #返回（0，0）、（0，1）、。。。

#用函数创建一个二维数组：只能创建二维以下
a = np.fromfunction(f,(5,4),dtype=int)  
print(a)
print('\n')

#索引
print(a[(3,2)]) #从0开始，第三行第二列的32
print('\n')

#切片
print(a[0:5 ,0]) #打印第一列的 第一行到第四行的元素
print('\n')

#高维矩阵切片法及其省略表示法：
b = np.arange(18).reshape(3,2,3) #创造一个3层2行3列的数组
print(b)
print('\n')
print(b[:,:,1])   #打印每层，每行的第1列（从0开始）
print('\n')
print(b[...,1])   #省略法
print('\n')
print(b[...,0,:]) #打印每层，每列，第0行
print('\n')


#遍历
for i in a:
    for j in i:
        print(j)  #遍历，打印出数列的所有元素
"""
for i in a.flat:
    print(i)
效果同上一样，因为 .flat 将矩阵切成一个一个一维数组
"""
        

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


32


[ 0 10 20 30 40]


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


[[ 1  4]
 [ 7 10]
 [13 16]]


[[ 1  4]
 [ 7 10]
 [13 16]]


[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]


0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


'\nfor i in a.flat:\n    print(i)\n效果同上一样，因为 .flat 将矩阵切成一个一个一维数组\n'

## 4、数组形状操作
### 1、改变数组形状

In [114]:
import numpy as np

a = np.arange(9).reshape((3,3))  #创建一个3行3列的数组
print(a)
print('\n')

# reshape(元组)改变形状而不会改变原数组
b = a.reshape((1,9))
print(b)
print(a)
print('\n')

y = a.reshape((1,-1))  #用 -1 将可以自动计算需要多少列
print(y)

# resize(元组)会改变原数组的形状
c = np.arange(18)
print(c)
d = c.resize((2,3,3))
print(d)  #无返回值
print(c)

#转置
t = a.T
print(t)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[0 1 2 3 4 5 6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[0 1 2 3 4 5 6 7 8]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
None
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


### 2、连接数组 
>1. （concatenate((数组们) ,axis=   )
>2. stack((数组们) ,数字表示轴：0，1...)
>3. vstack(行连接的数组们)
>4. hstack(列连接的数组们)
>5. r_（快速创建行数组） 
>6. c_（快速创建列数组））

In [133]:
import numpy as np

a = np.arange(4).reshape((2,2))
b = np.arange(4,8).reshape((2,2))
print(a)
print('\n')
print(b)
print('\n')

"""几种连接方式"""
c = np.concatenate((a,b),axis=1) #默认按 axis=0 连接
print(c)
print('\n')

d = np.stack((a,b),2) #沿新的轴堆叠两个数组
print(d)
print('\n')

v = np.vstack((a,b)) #等同与按 axis=1 连接
print(v)
print('\n')

h = np.hstack((a,b)) #等同于按 axis=0 连接
print(h)
print('\n')

r = np.r_[1:5,2,6] #快速创造行数组
print(r)
print('\n')

c = np.c_[1:5 ,2:6 ,3:7]  #快速创造列数组 【逗号内的值都得是同维度，即元素个数一致】
print(c)
print('\n')

[[0 1]
 [2 3]]


[[4 5]
 [6 7]]


[[0 1 4 5]
 [2 3 6 7]]


[[[0 4]
  [1 5]]

 [[2 6]
  [3 7]]]


[[0 1]
 [2 3]
 [4 5]
 [6 7]]


[[0 1 4 5]
 [2 3 6 7]]


[1 2 3 4 2 6]


[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]




### 3、分割数组
>1. np.split(数组，数或列表区间，轴axis=) :若中间为数 n 则将数组分为 n份 ，若中间为区间则以区间划分。
>2. np.hsplit(数组，数或列表区间)  :沿h分开
>3. np.vsplit(数组，数或列表区间)  :沿v分开

In [141]:
import numpy as np

# 创建一个4*4的数组
a = np.arange(16).reshape((4,4))
print("原数组：")
print(a)
print('\n')

#用split分割
b = np.split(a,2) #默认axis=0 ，沿轴0将数组分为2分
print(b)
print('\n')

c = np.split(a,[1,3],axis=1) #沿轴1将数组,将数组分为0列，1列到2列，3列
print(c)
print('\n')

#用hsplit分割
d = np.hsplit(a,2) #以h将数组分为2分
print(d)
print('\n')

e = np.hsplit(a,[1,3]) #以h将数组分为0列，1列到2列，3列
print(e)
print('\n')

#用vsplit分割
f = np.vsplit(a,2) #以v将数组分为2分
print(f)
print('\n')

g = np.vsplit(a,[1,3]) #以v将数组分为0行，1行到2行，3行
print(g)
print('\n')

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]




## 5、视图view 拷贝copy
>**1. 视图是对原数据的引用，不产生副本。**
>>1. 当赋值（a=b）时，a，b为同一个id，修改b则会相应修改a；
>>2. 当切片（b=a[:3]）时，修改切片也会影响到a；
>>3. 当视图时（b=a.view()）,a,b的id不同，修改b的形状并不会影响a的形状，但是修改b的值会影响a的值
>**2. 拷贝时对原数据创造副本，与原数据完全脱钩。**
>>1. 拷贝（b=a.copy()）

In [16]:
import numpy as np

#创造一个4*4矩阵
a = np.arange(16).reshape((4,4))
print(a)
print('\n')

#赋值操作
b = a
print("b的id：" ,id(b))
print("a的id：" ,id(a))
print('\n')

#切片操作
c = a[1:3,0:2]
print(c)
print("c的id：" ,id(c))
print("a的id：" ,id(a))
print('修改c的值将会影响a')
c[0,0] = 100
print(c)
print(a)
print('\n')

#视图操作
d = a.view()
print(d)
print("d的id：" ,id(d))
print("a的id：" ,id(a))
print('\n')
print('改变d的形状不影响a，但是改变d的值会影响a')
d = d.reshape((2,8))
print(d)
print(a)
print('\n')
d[0,0] = 300
print(d)
print(a)
print('\n')

#复制操作，将生成与原数据完全脱钩的副本
e = a.copy()
print(e)

f = a[1:3,0:2].copy() #甚至能copy切片
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


b的id： 2292759141808
a的id： 2292759141808


[[4 5]
 [8 9]]
c的id： 2292759141232
a的id： 2292759141808
修改c的值将会影响a
[[100   5]
 [  8   9]]
[[  0   1   2   3]
 [100   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]


[[  0   1   2   3]
 [100   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]
d的id： 2292759140848
a的id： 2292759141808


改变d的形状不影响a，但是改变d的值会影响a
[[  0   1   2   3 100   5   6   7]
 [  8   9  10  11  12  13  14  15]]
[[  0   1   2   3]
 [100   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]


[[300   1   2   3 100   5   6   7]
 [  8   9  10  11  12  13  14  15]]
[[300   1   2   3]
 [100   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]


[[300   1   2   3]
 [100   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]
[[100   5]
 [  8   9]]


还有许多数组的操作函数可以查阅：https://numpy.org/doc/stable/reference/routines.html#routines 或 https://www.runoob.com/numpy/numpy-tutorial.html

## 6、广播原理 broadcasting
### 用来处理两个形状不同的数组的运算，使形状不同的数组的形状变一致
>**1. 两数组维度不相同，但在某维度具有相同的元素数：**
>>![bc](https://numpy.org/doc/stable/_images/broadcasting_2.png)
>**2. 两数组维度相同，但双方都有元素数为一的维度：**
>>![bc](https://numpy.org/doc/stable/_images/broadcasting_4.png)
>**3. 两数组不仅维度不相同，也没有相同的元素数，则广播会报错：**
>>![bc](https://numpy.org/doc/stable/_images/broadcasting_3.png)

## 7、高级索引与索引技巧
> **索引也可以用整数数组和布尔数组索引**

In [41]:
import numpy as np

#创建一个8*4的数组
a = np.arange(32).reshape(8,4)
print(a)
print('\n')

"""用整数数组索引"""
#用整数数组索引四个角的元素
#方法一：a【【0轴坐标】，【1轴坐标】】
b = a[[0,0,7,7],[0,3,0,3]]
print(b)
print('\n')

#方法二：a【【0轴坐标矩阵】，【1轴坐标矩阵】】
row = np.array([[0,0],[7,7]])
print(row)
column = np.array([[0,3],[0,3]])
print(column)
print('\n')
c = a[row,column]
print(c)
print('\n')

#方法三：可以结合 ... 和 ：来索引
d = np.array([[1,2,3], [4,5,6],[7,8,9]])
e = d[1:3, 1:3]
f = d[1:3,[1,2]]
g = d[...,1:]
print(e)
print(f)
print(g)
print('\n')
""""""""""""""""""""""""""""""""""""""""""""""""

"""用布尔索引"""
d = a[ 8<a]
print(d)

e = a>8
e
print(a[e])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


[ 0  3 28 31]


[[0 0]
 [7 7]]
[[0 3]
 [0 3]]


[[ 0  3]
 [28 31]]


[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
